### ISSUE TITLE
No Backend Available 

### ISSUE THREAD

**Issue by sdaravath** [marcojob/BQ40Z50_Analyzer#4]
Hi Marco,

I used your code for Battery Fuel gauge bq40z50 and EV2300 usb to analyze some of the parameters from the register,
however after running main.py  I getting an error " No backend available " issue.
can you please advise how to read Lifetime date or whichever is working parameter to analyze.

Regards,
Suresh

**Comment by marcojob** [comment]
This seems to be a Windows issue, try to follow this [solution](https://github.com/pyusb/pyusb/issues/120) . Closing here.
